package com.example.braincircle.model.data

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Represents a chat message in group chat sub-collection.
 *
 * @param messageId Unique identifier for the message (autogenerated).
 * @param groupId Identifier of the group the message belongs to.
 * @param senderId Identifier of the sender.
 * @param senderName Name of the sender.
 * @param text Text content of the message.
 * @param timestamp Timestamp indicating when the message was sent.
 */
data class ChatMessage(
    @DocumentId val messageId: String = "",
    val groupId: String = "",
    val senderId: String = "",
    val senderName: String = "",
    val text: String = "",
    @ServerTimestamp val timestamp: Date? = null
)
