package com.example.braincircle.model.data

import com.google.firebase.firestore.DocumentId
import java.util.Date

/**
 * Model for a study group.
 *
 * @param groupId The unique identifier for the study group (autogenerated).
 * @param name The name of the study group.
 * @param courseCode The unique identifier for the course associated with the study group.
 * @param courseTitle The title of the course associated with the study group.
 * @param courseDept The department that offers the course associated with the study group.
 * @param adminId The uid for the admin of the study group.
 * @param members A list of uids for the members of the study group.
 * @param description A description of the study group.
 * @param locationName Name of the location of the meeting or class.
 * @param locationLink Location of the meeting or class.
 * @param meetingDate Date and time of the meeting or class.
 */
data class StudyGroup(
    @DocumentId val groupId: String = "",
    val name: String = "",
    val courseCode: String = "",
    val courseTitle: String = "",
    val courseDept: String = "",
    val adminId: String = "",
    val members: List<String> = emptyList(),
    val description: String = "",
    val locationName: String = "",
    val locationLink: String = "",
    val meetingDate: Date? = null
)
